// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7tz2DRBUyKQ4v3JAHQAjSFDRnXCwnrqo',
    appId: '1:422287132056:web:a15f5e4f8acb0a8212d7ed',
    messagingSenderId: '422287132056',
    projectId: 'clean-framework-firebase-expl',
    authDomain: 'clean-framework-firebase-expl.firebaseapp.com',
    storageBucket: 'clean-framework-firebase-expl.appspot.com',
    measurementId: 'G-512DJSKTDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhDMMhUCGpiFIn-ACkQX1rqmgpPaOzvWI',
    appId: '1:422287132056:android:d21ebf80d7e10f7812d7ed',
    messagingSenderId: '422287132056',
    projectId: 'clean-framework-firebase-expl',
    storageBucket: 'clean-framework-firebase-expl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqyUReGL8Vd0a2vzL4kyoLTfmOf0hg0vs',
    appId: '1:422287132056:ios:d292ee94eec3373712d7ed',
    messagingSenderId: '422287132056',
    projectId: 'clean-framework-firebase-expl',
    storageBucket: 'clean-framework-firebase-expl.appspot.com',
    iosBundleId: 'com.example.themeExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqyUReGL8Vd0a2vzL4kyoLTfmOf0hg0vs',
    appId: '1:422287132056:ios:df750890c3db0b9412d7ed',
    messagingSenderId: '422287132056',
    projectId: 'clean-framework-firebase-expl',
    storageBucket: 'clean-framework-firebase-expl.appspot.com',
    iosBundleId: 'com.example.themeExample.RunnerTests',
  );
}
